# Common config Template 重复的通用的配置抽离在到
spring:
  profiles: __BK_CODECC_PROFILE__
  application:
    version: 4.0.0
  # consul config do not need to change
  redis:
    host: __BK_CODECC_REDIS_HOST__
    password: __BK_CODECC_REDIS_PASSWORD__
    port: __BK_CODECC_REDIS_PORT__
    database: __BK_CODECC_REDIS_DB__
    pool:
      maxActive: 16
      maxWait: -1
      maxIdle: 16
      minIdle: 0
  rabbitmq:
    virtual-host: __BK_CODECC_RABBITMQ_VHOST__
    username: __BK_CODECC_RABBITMQ_USER__
    password: __BK_CODECC_RABBITMQ_PASSWORD__
    addresses: __BK_CODECC_RABBITMQ_ADDR__
    listener:
      simple:
        concurrency: 10
        acknowledge-mode: auto
    core:
      virtual-host: __BK_CODECC_RABBITMQ_VHOST__
      username: __BK_CODECC_RABBITMQ_USER__
      password: __BK_CODECC_RABBITMQ_PASSWORD__
      addresses: __BK_CODECC_RABBITMQ_ADDR__
    extend:
      virtual-host: __BK_CODECC_RABBITMQ_VHOST__
      username: __BK_CODECC_RABBITMQ_USER__
      password: __BK_CODECC_RABBITMQ_PASSWORD__
      addresses: __BK_CODECC_RABBITMQ_ADDR__
  cloud:
    consul:
      discovery:
        tags: __BK_CODECC_CONSUL_DISCOVERY_TAG__
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
      port: __BK_CODECC_CONSUL_HTTP_PORT__
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# http concurrency
server:
  servlet-path: /
  undertow:
    worker-threads: 100


# monitor path config
management:
  security:
    enabled: false
  context-path: /management

devopsGateway:
  host: __BK_CI_PUBLIC_HOST__
  idchost: __BK_CI_PUBLIC_HOST__

codecc:
  gateway:
    host: __BK_CODECC_PUBLIC_HOST__

service:
  suffix:
    ci: "__BK_CODECC_CI_SERVICE_SUFFIX_TAG__"
    codecc: "__BK_CODECC_SERVICE_SUFFIX_TAG__"

