# 服务配置文件模板
spring:
  application:
    name: coverity
    desc: Coverity Service
    version: 4.0.0
    packageName: com.tencent.bk.codecc.coverity
  #      port: 8080
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同
server:
  port:  # 服务端口
